/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_progra;

/**
 *
 * @author erick
 */
public class Historial extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Historial.class.getName());
    private Usuario usuarioActual;
    private javax.swing.table.DefaultTableModel modeloTabla;
    private pantalla_bancaria ventanaAnterior;

    /**
     * Creates new form Historial
     */
    public Historial() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Historial(Usuario usuario, pantalla_bancaria ventana) {
    initComponents();
    this.usuarioActual   = usuario;
    this.ventanaAnterior = ventana; // Guarda la referencia a la ventana anterior
    jLabelUsuario.setText("Historial de: " + usuario.getUsername());
    configurarTabla();
    cargarHistorial();
    jButtonTranseferir.addActionListener(e -> transferir());
    jButtonVolver.addActionListener(e -> volver());
            this.setLocationRelativeTo(null);

}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextDestino = new javax.swing.JTextField();
        jTextMonto = new javax.swing.JTextField();
        jTextDescription = new javax.swing.JTextField();
        jButtonVolver = new javax.swing.JButton();
        jButtonTranseferir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco Chepito - Historial de transacciones");

        jPanel1.setBackground(new java.awt.Color(30, 58, 131));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("jLabel1");
        jLabelUsuario.setToolTipText("");
        jPanel1.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 6, -1, -1));

        jTextDestino.setBackground(new java.awt.Color(255, 255, 255));
        jTextDestino.setColumns(15);
        jTextDestino.setForeground(new java.awt.Color(148, 163, 184));
        jTextDestino.setText("Destino");
        jTextDestino.setToolTipText("");
        jTextDestino.setName("jTextDestino"); // NOI18N
        jTextDestino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextDestinoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDestinoFocusLost(evt);
            }
        });
        jTextDestino.addActionListener(this::jTextDestinoActionPerformed);
        jPanel1.add(jTextDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 26));
        jTextDestino.getAccessibleContext().setAccessibleName("");

        jTextMonto.setBackground(new java.awt.Color(255, 255, 255));
        jTextMonto.setColumns(15);
        jTextMonto.setForeground(new java.awt.Color(148, 163, 184));
        jTextMonto.setText("Monto (Q)");
        jTextMonto.setName(""); // NOI18N
        jTextMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextMontoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextMontoFocusLost(evt);
            }
        });
        jPanel1.add(jTextMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, 26));

        jTextDescription.setBackground(new java.awt.Color(255, 255, 255));
        jTextDescription.setColumns(15);
        jTextDescription.setForeground(new java.awt.Color(148, 163, 184));
        jTextDescription.setText("Descripción");
        jTextDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextDescriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDescriptionFocusLost(evt);
            }
        });
        jPanel1.add(jTextDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 40, -1, 26));

        jButtonVolver.setBackground(new java.awt.Color(16, 185, 129));
        jButtonVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("VOLVER");
        jButtonVolver.setBorderPainted(false);
        jButtonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVolver.setFocusPainted(false);
        jButtonVolver.addActionListener(this::jButtonVolverActionPerformed);
        jPanel1.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, 26));

        jButtonTranseferir.setBackground(new java.awt.Color(16, 185, 129));
        jButtonTranseferir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTranseferir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTranseferir.setText("TRANSFERIR");
        jButtonTranseferir.setBorderPainted(false);
        jButtonTranseferir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTranseferir.setFocusPainted(false);
        jPanel1.add(jButtonTranseferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, 26));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(148, 163, 184)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 69, 780, 343));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDestinoActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        volver();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jTextDestinoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDestinoFocusGained
        // TODO add your handling code here:
        if (jTextDestino.getText().equals("Destino")) {
        jTextDestino.setText("");
        jTextDestino.setForeground(new java.awt.Color(51, 65, 85)); // Cambia a color de texto oscuro real
        }
    }//GEN-LAST:event_jTextDestinoFocusGained

    private void jTextDestinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDestinoFocusLost
        // TODO add your handling code here:
        if (jTextDestino.getText().isEmpty()) {
        jTextDestino.setText("Destino");
        jTextDestino.setForeground(new java.awt.Color(148, 163, 184)); // Vuelve al color gris de pista
        }
    }//GEN-LAST:event_jTextDestinoFocusLost

    private void jTextMontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextMontoFocusGained
        // TODO add your handling code here:
        if (jTextMonto.getText().equals("Monto (Q)")) {
        jTextMonto.setText("");
        jTextMonto.setForeground(new java.awt.Color(51, 65, 85)); // Cambia a color de texto oscuro real
        }
    }//GEN-LAST:event_jTextMontoFocusGained

    private void jTextMontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextMontoFocusLost
        // TODO add your handling code here:
        if (jTextMonto.getText().isEmpty()) {
        jTextMonto.setText("Monto (Q)");
        jTextMonto.setForeground(new java.awt.Color(148, 163, 184)); // Vuelve al color gris de pista
        }
    }//GEN-LAST:event_jTextMontoFocusLost

    private void jTextDescriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDescriptionFocusGained
        // TODO add your handling code here:
        if (jTextDescription.getText().equals("Descripción")) {
        jTextDescription.setText("");
        jTextDescription.setForeground(new java.awt.Color(51, 65, 85)); // Cambia a color de texto oscuro real
        }
    }//GEN-LAST:event_jTextDescriptionFocusGained

    private void jTextDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDescriptionFocusLost
        // TODO add your handling code here:
        if (jTextDescription.getText().isEmpty()) {
        jTextDescription.setText("Descripción");
        jTextDescription.setForeground(new java.awt.Color(148, 163, 184)); // Vuelve al color gris de pista
        }
    }//GEN-LAST:event_jTextDescriptionFocusLost
    
    
    /**
     * @param args the command line arguments
     */
    private void configurarTabla() {
    // Define los títulos de las 4 columnas de la tabla
    String[] columnas = {"Destino", "Monto", "Fecha", "Descripción"};
    
    modeloTabla = new javax.swing.table.DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Evita que el usuario edite celdas directamente
        }
    };
    jTable1.setModel(modeloTabla); // Le asigna el modelo a la tabla visual
}
    private void cargarHistorial() {
    modeloTabla.setRowCount(0); // Borra las filas anteriores para no duplicar
    
    // Consulta SQLite y por cada resultado agrega una fila a la tabla
    for (Object[] fila : TransferenciaDAO.obtenerPorUsuario(usuarioActual.getId())) {
        modeloTabla.addRow(fila);
    }
}
private void transferir() {
    String destino     = jTextDestino.getText().trim();
    String montoTexto  = jTextMonto.getText().trim();
    String descripcion = jTextDescription.getText().trim();

    if (destino.isEmpty() || montoTexto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Destino y monto son obligatorios.",
            "Campos vacíos",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validar que no se transfiera a sí mismo
    if (destino.equalsIgnoreCase(usuarioActual.getUsername())) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "No puedes transferirte dinero a ti mismo.",
            "Destino inválido",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        double monto = Double.parseDouble(montoTexto);

        if (monto <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El monto debe ser mayor a cero.",
                "Monto inválido",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (monto > usuarioActual.getSaldo()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Saldo insuficiente.\nSaldo actual: Q" +
                String.format("%.2f", usuarioActual.getSaldo()),
                "Sin fondos",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Llama al nuevo registrar() que maneja ambos usuarios
        boolean exito = TransferenciaDAO.registrar(
            usuarioActual, destino, monto, descripcion
        );

        if (exito) {
            jTextDestino.setText("");
            jTextMonto.setText("");
            jTextDescription.setText("");
            cargarHistorial();

            javax.swing.JOptionPane.showMessageDialog(this,
                "¡Transferencia exitosa!\nNuevo saldo: Q" +
                String.format("%.2f", usuarioActual.getSaldo()),
                "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El usuario '" + destino + "' no existe.\nVerifica el nombre.",
                "Usuario no encontrado",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "El monto debe ser un número válido.\nEjemplo: 150.00",
            "Formato inválido",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
    private void volver() {
    ventanaAnterior.actualizarSaldo(usuarioActual); // Refresca el saldo
    ventanaAnterior.setVisible(true); // Muestra la ventana que ya existía
    this.dispose();
}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Historial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTranseferir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextDescription;
    private javax.swing.JTextField jTextDestino;
    private javax.swing.JTextField jTextMonto;
    // End of variables declaration//GEN-END:variables
}
