/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_progra;

/**
 *
 * @author erick
 */
public class Historial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Historial.class.getName());
    private Usuario usuarioActual;
    private javax.swing.table.DefaultTableModel modeloTabla;

    /**
     * Creates new form Historial
     */
    public Historial() {
        initComponents();
    }
    public Historial(Usuario usuario) {
    initComponents();              // Dibuja el formulario (siempre va primero)
    this.usuarioActual = usuario;  // Guarda quién inició sesión
    jLabelUsuario.setText("Historial de: " + usuario.getUsername()); // Muestra el nombre
    configurarTabla();             // Prepara las columnas de la tabla
    cargarHistorial();             // Trae los datos de SQLite y los muestra

    // Conecta los botones con sus métodos
    jButtonTranseferir.addActionListener(e -> transferir());
    jButtonVolver.addActionListener(e -> volver());
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextDestino = new javax.swing.JTextField();
        jTextMonto = new javax.swing.JTextField();
        jTextDescription = new javax.swing.JTextField();
        jButtonVolver = new javax.swing.JButton();
        jButtonTranseferir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelUsuario.setText("jLabel1");
        jLabelUsuario.setToolTipText("");

        jTextDestino.setColumns(15);
        jTextDestino.setText("Destino");
        jTextDestino.setToolTipText("");
        jTextDestino.setName("jTextDestino"); // NOI18N
        jTextDestino.addActionListener(this::jTextDestinoActionPerformed);

        jTextMonto.setColumns(15);
        jTextMonto.setText("Monto");
        jTextMonto.setName(""); // NOI18N

        jTextDescription.setColumns(15);
        jTextDescription.setText("Descripción");

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(this::jButtonVolverActionPerformed);

        jButtonTranseferir.setText("Transferir");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUsuario)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonTranseferir)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonVolver)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVolver)
                    .addComponent(jButtonTranseferir))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextDestino.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDestinoActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        pantalla_bancaria pb = new pantalla_bancaria();
        pb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    private void configurarTabla() {
    // Define los títulos de las 4 columnas de la tabla
    String[] columnas = {"Destino", "Monto", "Fecha", "Descripción"};
    
    modeloTabla = new javax.swing.table.DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Evita que el usuario edite celdas directamente
        }
    };
    jTable1.setModel(modeloTabla); // Le asigna el modelo a la tabla visual
}
    private void cargarHistorial() {
    modeloTabla.setRowCount(0); // Borra las filas anteriores para no duplicar
    
    // Consulta SQLite y por cada resultado agrega una fila a la tabla
    for (Object[] fila : TransferenciaDAO.obtenerPorUsuario(usuarioActual.getId())) {
        modeloTabla.addRow(fila);
    }
}
    private void transferir() {
    // Lee lo que el usuario escribió en los campos
    String destino     = jTextDestino.getText().trim();
    String montoTexto  = jTextMonto.getText().trim();
    String descripcion = jTextDescription.getText().trim();

    // Validación 1: campos obligatorios no vacíos
    if (destino.isEmpty() || montoTexto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Destino y monto son obligatorios.",
            "Campos vacíos",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return; // Para aquí si hay error
    }

    try {
        double monto = Double.parseDouble(montoTexto); // Convierte texto a número

        // Validación 2: monto positivo
        if (monto <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El monto debe ser mayor a cero.",
                "Monto inválido",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validación 3: saldo suficiente
        if (monto > usuarioActual.getSaldo()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Saldo insuficiente.\nSaldo actual: Q" +
                String.format("%.2f", usuarioActual.getSaldo()),
                "Sin fondos",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Todo OK: guarda en SQLite
        TransferenciaDAO.registrar(
            usuarioActual.getId(), destino, monto, descripcion
        );

        // Descuenta el saldo en memoria
        usuarioActual.setSaldo(usuarioActual.getSaldo() - monto);

        // ✅ Guarda el nuevo saldo en SQLite
        UsuarioDAO.actualizarSaldo(usuarioActual.getId(), usuarioActual.getSaldo());

        // Limpia los campos del formulario
        jTextDestino.setText("");
        jTextMonto.setText("");
        jTextDescription.setText("");
        
        cargarHistorial(); // Recarga la tabla con la nueva transferencia

        javax.swing.JOptionPane.showMessageDialog(this,
            "¡Transferencia exitosa!\nNuevo saldo: Q" +
            String.format("%.2f", usuarioActual.getSaldo()),
            "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException e) {
        // Se dispara si escriben letras en el campo monto
        javax.swing.JOptionPane.showMessageDialog(this,
            "El monto debe ser un número válido.\nEjemplo: 150.00",
            "Formato inválido",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
    private void volver() {
    // Abre pantalla_bancaria pasando el usuario con el saldo actualizado
    pantalla_bancaria pb = new pantalla_bancaria(usuarioActual);
    pb.setVisible(true);
    this.dispose(); // Cierra esta ventana
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Historial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTranseferir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextDescription;
    private javax.swing.JTextField jTextDestino;
    private javax.swing.JTextField jTextMonto;
    // End of variables declaration//GEN-END:variables
}
